sonar.projectKey=fr.nirahtech.devops-drink

sonar.host.url=http://172.17.0.1:9000
sonar.token=sqa_7094149517a00b56e0f7124a09094ee9559c73ad

sonar.java.binaries=target/classes
sonar.exclusions=**.db,**.yaml,**.properties
