spring.application.name=devops

# Connexion BDD
spring.datasource.url=jdbc:postgresql://172.17.0.1:5432/devops
spring.datasource.username=devops
spring.datasource.password=devops
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
